name: choquet_env
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.10
  
  # Core scientific computing
  - numpy
  - scipy
  - pandas
  
  # Machine learning libraries
  - scikit-learn
  - imbalanced-learn
  - joblib
    
  # Image processing and geospatial
  - rasterio
  - scikit-image
  
  # Data storage
  - h5py
  
  # Visualization
  - matplotlib
  - tqdm
  
  # Command line interface
  - click
  
  # Additional utilities
  - pyyaml
  
  # Pip packages (if not available in conda)
  - pip
  - pip:
    - tqdm
